### ISSUE TITLE
The datasets 'Dropbox folder' can not open

### ISSUE THREAD

**Issue by HanBing0802** [mit-acl/cadrl_ros#14]
Hey Michael,
I try to open the datasets in the Dropbox folder but it doesn't work, can you give me a new website about it?
Thank you very much!
Happy new year to you!
Bing Han

**Comment by mfe7** [comment]
what's the error? the dropbox links work for me -- I could send via email if dropbox is the issue

**Comment by HanBing0802** [comment]
thank you very much! My email is bhan0458@bjtu.edu.cn
Maybe it can not open due  to my network.
