### ISSUE TITLE
About the training set.

### ISSUE THREAD

**Issue by chenzhiwo** [mit-acl/cadrl_ros#2]
How can I obtain the initial training set that the paper say that is relased to the public?

**Comment by mfe7** [comment]
Thanks for pointing this out. I have just uploaded the files and some instructions to a Dropbox folder: https://www.dropbox.com/sh/yu1spzhhj8c9akl/AAALo8yXSfQ1nxaU2KFRGWuTa?dl=0

I have also added this info to this repo's readme. Let me know if there are any questions.

**Comment by chenzhiwo** [comment]
Thanks!

**Comment by chenzhiwo** [comment]
Here is a little problem, the `dataset_readme.txt` said that `states.shape ---> (100000, 26)`, however, for the regular dataset, `states.shape` should be `(100000, 28)`.

**Comment by chenzhiwo** [comment]
Just a little confusing, thank you!

**Comment by mfe7** [comment]
Take a look at the description of the state array for the two styles of
observations. One has 26 elements and the other has 28

Good point, I’ll try to make that more clear
