### ISSUE TITLE
./build_docker.sh error!

### ISSUE THREAD

**Issue by nfhe** [mit-acl/cadrl_ros#20]
Hello, thanks for sharing your awesome work. I'm a beginner about this field and this is the first time I learn about it. I have been troubled by the above questions for a long time. I hope you can help me, thank you very much!

When I run**. / build_ docker. SH**, there is an error when **pip install IPython = = 5.7 ipykannel = = 4.10 jupyter**.

![1659964507(1)](https://user-images.githubusercontent.com/92715669/183426605-84ff36a9-3819-42c5-878d-ff4a7ff28561.png)

I don't how to solve it.
Thank you very much!

**Comment by mfe7** [comment]
I'm not sure about this one, seems beyond the scope of this repo.

Also, it is recommended to paste the text of the error in a code block (`like this`), rather than paste an image, so that it's easier to search for similar errors.

**Comment by nfhe** [comment]
Thank you very much for your reply. I have been debugging the docker environment recently, and the version has changed a lot now, so I have modified some of the contents of the Dockerfile file and briefly explained it here to facilitate future calls.


**I am using ubuntu18.04**

**1.# FROM nvidia/cuda**
FROM nvidia/cuda:10.2-devel-ubuntu18.04

**2.**
RUN pip install protobuf==3.17.3

**3.**
RUN pip2 install terminado==0.8.3

**4.**
RUN pip2 install jsonschema==2.6.0

**5.**
RUN pip install qtconsole==4.7.6

Thanks again to the author. If I have scientific research results, I will add this citation. I hope I can have the opportunity to communicate more in the future.

**Comment by nfhe** [comment]
Hello, I successfully run roslaunch this time. However, I have a little doubt about the use of jackal ground robot to provide ROS testing as described in the depo. However, I have not found a tutorial on how to make the robot run in the gazebo environment using the algorithm provided by you. I'm very glad if you can help me. Thank you.
