### ISSUE TITLE
Some problems about how to replicate the results 

### ISSUE THREAD

**Issue by George-Lu-ZA** [mit-acl/cadrl_ros#25]
Hi, I am very interested in this project and I really want to replicate the figures shown in the paper. 
However, after I isntall the dependency and run the  jupyter example code, I find the example is a little bit simple, which I mean it just show how to load the net and give a action prediction in a moment. 
I wonder if there are some decumentation or code that show how to use the network, agent and util python file to draw a obstacle avoidance figure just like shown in the paper. I am also curious about how to use the data in the dataset you provided along with the already existed network module in the code to give some results. 
Hope I describe my problems clearly. Thank you.

**Comment by mfe7** [comment]
this repo is just a ros wrapper for the policy whereas [this gym repo](https://github.com/mit-acl/gym-collision-avoidance) has more of what it sounds like you're looking for

**Comment by George-Lu-ZA** [comment]
Ok, I will look at that repo. Thanks for your reply!



---- Replied Message ----
| From | Michael ***@***.***> |
| Date | 05/17/2023 23:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mit-acl/cadrl_ros] Some problems about how to replicate the results (Issue #25) |

this repo is just a ros wrapper for the policy whereas this gym repo has more of what it sounds like you're looking for
