### ISSUE TITLE
How to consider map?

### ISSUE THREAD

**Issue by CAI23sbP** [mit-acl/cadrl_ros#26]
How are you @mfe7?
I have found "Robot designed for socially acceptable navigation", and i read it. 
I have a single question about diffusion map in page 48.
-> How to merge diffusion map and CADRL?

I understood that like under.
First using grid map for making Diffusion map, then input them into a  MPC.
The MPC generate trajectories which are able to avoid collision with map.
A CADRL uses Trajectory, best to drive, for subgoal.
In this view, the CADRL is used for  tracking module?

Thank you for reading this issue.

**Comment by mfe7** [comment]
the way we used diffusion map and cadrl together in that thesis (from 2017) is: build a 2d occupancy map of the environment ahead of time, then online: given a global goal coordinate, repeatedly use the diffusion map algorithm to choose a subgoal 5-10m ahead of the robot's position that should lead toward the global goal (accounting for static obstacles in the prior map), then pass the current subgoal to CADRL to select a velocity vector (considering the dynamic obstacles in the present environment).

**Comment by CAI23sbP** [comment]
Thank you for your reply
