### ISSUE TITLE
NNActions and PlannerMode messages

### ISSUE THREAD

**Issue by Lapjeskater** [mit-acl/cadrl_ros#6]
Hey Michael,

I'm trying to run the rosnode, but I get an error that the NNActions and PlannerMode messages do not exists. I also couldn't find them in the ford_msgs repo. Do I strictly need the messages or can I remove them from the code?  

Kind regards, Ewoud

**Comment by mfe7** [comment]
Hi @Lapjeskater  - those messages are defined in the `dev` branch of ford_msgs if you do want to try to use them. However, NNActions doesn't have any purpose so it can be removed -- right now it sets `self.feasible_actions` which is never used elsewhere. PlannerMode is supposed to allow an external state machine to switch between various planners, but for the sake of this code you could just set `self.operation_mode` upon initializing the node to the `NN mode`. Let me know if that's unclear. I will try to update/remove these from this version of the code at some point.
